install:
  - gem install awesome_bot

script:
  - awesome_bot README.md
      --allow-dupe
      --allow-redirect
      --allow-timeout
      --set-timeout 10
      --skip-save-results
      --white-list braid.io,customelements.io,meatscope.camera,olacabs.com,snapdrop.net,victoriassecret.com
